instrs = {
 'ABS.FMT': [{'instr': 'ABS.FMT',
              'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
              'short': 'Floating Point Absolute Value'}],
 'ADD': [{'instr': 'ADD',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Add Word'}],
 'ADD.FMT': [{'instr': 'ADD.FMT',
              'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
              'short': 'Floating Point Add'}],
 'ADDI': [{'instr': 'ADDI',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Add Immediate Word'}],
 'ADDIU': [{'instr': 'ADDIU',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Add Immediate Unsigned Word'}],
 'ADDU': [{'instr': 'ADDU',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Add Unsigned Word'}],
 'AND': [{'instr': 'AND',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'And'}],
 'ANDI': [{'instr': 'ANDI',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'And Immediate'}],
 'B': [{'instr': 'B',
        'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
        'short': 'Unconditional Branch'}],
 'BAL': [{'instr': 'BAL',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Branch and Link'}],
 'BC1F': [{'instr': 'BC1F',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Branch on FP False'}],
 'BC1FL': [{'instr': 'BC1FL',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Branch on FP False Likely'}],
 'BC1T': [{'instr': 'BC1T',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Branch on FP True'}],
 'BC1TL': [{'instr': 'BC1TL',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Branch on FP True Likely'}],
 'BC2F': [{'instr': 'BC2F',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Branch on COP2 False'}],
 'BC2FL': [{'instr': 'BC2FL',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Branch on COP2 False Likely'}],
 'BC2T': [{'instr': 'BC2T',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Branch on COP2 True'}],
 'BC2TL': [{'instr': 'BC2TL',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Branch on COP2 True Likely'}],
 'BEQ': [{'instr': 'BEQ',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Branch on Equal'}],
 'BEQL': [{'instr': 'BEQL',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Branch on Equal Likely'}],
 'BGEZ': [{'instr': 'BGEZ',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Branch on Greater Than or Equal to Zero'}],
 'BGEZAL': [{'instr': 'BGEZAL',
             'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
             'short': 'Branch on Greater Than or Equal to Zero and Link'}],
 'BGEZALL': [{'instr': 'BGEZALL',
              'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
              'short': 'Branch on Greater Than or Equal to Zero and Link Likely'}],
 'BGEZL': [{'instr': 'BGEZL',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Branch on Greater Than or Equal to Zero Likely'}],
 'BGTZ': [{'instr': 'BGTZ',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Branch on Greater Than Zero'}],
 'BGTZL': [{'instr': 'BGTZL',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Branch on Greater Than Zero Likely'}],
 'BLEZ': [{'instr': 'BLEZ',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Branch on Less Than or Equal to Zero'}],
 'BLEZL': [{'instr': 'BLEZL',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Branch on Less Than or Equal to Zero Likely'}],
 'BLTZ': [{'instr': 'BLTZ',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Branch on Less Than Zero'}],
 'BLTZAL': [{'instr': 'BLTZAL',
             'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
             'short': 'Branch on Less Than Zero and Link'}],
 'BLTZALL': [{'instr': 'BLTZALL',
              'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
              'short': 'Branch on Less Than Zero and Link Likely'}],
 'BLTZL': [{'instr': 'BLTZL',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Branch on Less Than Zero Likely'}],
 'BNE': [{'instr': 'BNE',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Branch on Not Equal'}],
 'BNEL': [{'instr': 'BNEL',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Branch on Not Equal Likely'}],
 'BREAK': [{'instr': 'BREAK',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Breakpoint'}],
 'C.COND.FMT': [{'instr': 'C.COND.FMT',
                 'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
                 'short': 'Floating Point Compare'}],
 'CACHE': [{'instr': 'CACHE',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Perform Cache Operation'}],
 'CEIL.W.FMT': [{'instr': 'CEIL.W.FMT',
                 'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
                 'short': 'Floating Point Ceiling Convert to Word Fixed Point'}],
 'CFC1': [{'instr': 'CFC1',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move Control Word from Floating Point'}],
 'CFC2': [{'instr': 'CFC2',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move Control Word from Coprocessor 2'}],
 'CLO': [{'instr': 'CLO',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Count Leading Ones in Word'}],
 'CLZ': [{'instr': 'CLZ',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Count Leading Zeros in Word'}],
 'COP2': [{'instr': 'COP2',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Coprocessor Operation to Coprocessor 2'}],
 'CTC1': [{'instr': 'CTC1',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move Control Word to Floating Point'}],
 'CTC2': [{'instr': 'CTC2',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move Control Word to Coprocessor 2'}],
 'CVT.D.FMT': [{'instr': 'CVT.D.FMT',
                'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
                'short': 'Floating Point Convert to Double Floating Point'}],
 'CVT.S.FMT': [{'instr': 'CVT.S.FMT',
                'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
                'short': 'Floating Point Convert to Single Floating Point'}],
 'CVT.W.FMT': [{'instr': 'CVT.W.FMT',
                'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
                'short': 'Floating Point Convert to Word Fixed Point'}],
 'DERET': [{'instr': 'DERET',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Debug Exception Return'}],
 'DIV': [{'instr': 'DIV',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Divide Word'}],
 'DIV.FMT': [{'instr': 'DIV.FMT',
              'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
              'short': 'Floating Point Divide'}],
 'DIVU': [{'instr': 'DIVU',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Divide Unsigned Word'}],
 'ERET': [{'instr': 'ERET',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Exception Return'}],
 'FLOOR.W.FMT': [{'instr': 'FLOOR.W.FMT',
                  'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
                  'short': 'Floating Point Floor Convert to Word Fixed Point'}],
 'J': [{'instr': 'J',
        'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
        'short': 'Jump'}],
 'JAL': [{'instr': 'JAL',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Jump and Link'}],
 'JALR': [{'instr': 'JALR',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Jump and Link Register'}],
 'JR': [{'instr': 'JR',
         'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
         'short': 'Jump Register'}],
 'LB': [{'instr': 'LB',
         'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
         'short': 'Load Byte'}],
 'LBU': [{'instr': 'LBU',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Load Byte Unsigned'}],
 'LDC1': [{'instr': 'LDC1',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Load Doubleword to Floating Point'}],
 'LDC2': [{'instr': 'LDC2',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Load Doubleword to Coprocessor 2'}],
 'LH': [{'instr': 'LH',
         'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
         'short': 'Load Halfword'}],
 'LHU': [{'instr': 'LHU',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Load Halfword Unsigned'}],
 'LL': [{'instr': 'LL',
         'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
         'short': 'Load Linked Word'}],
 'LUI': [{'instr': 'LUI',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Load Upper Immediate'}],
 'LW': [{'instr': 'LW',
         'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
         'short': 'Load Word'}],
 'LWC1': [{'instr': 'LWC1',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Load Word to Floating Point'}],
 'LWC2': [{'instr': 'LWC2',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Load Word to Coprocessor 2'}],
 'LWL': [{'instr': 'LWL',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Load Word Left'}],
 'LWR': [{'instr': 'LWR',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Load Word Right'}],
 'MADD': [{'instr': 'MADD',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Multiply and Add Word to Hi, Lo'}],
 'MADD.FMT': [{'instr': 'MADD.FMT',
               'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
               'short': 'Floating Point Multiply Add'}],
 'MADDU': [{'instr': 'MADDU',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Multiply and Add Unsigned Word to Hi, Lo'}],
 'MFC0': [{'instr': 'MFC0',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move from Coprocessor 0'}],
 'MFC1': [{'instr': 'MFC1',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move Word from Floating Point'}],
 'MFC2': [{'instr': 'MFC2',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move Word from Coprocessor 2'}],
 'MFHI': [{'instr': 'MFHI',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move From HI Register'}],
 'MFLO': [{'instr': 'MFLO',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move From LO Register'}],
 'MOV.FMT': [{'instr': 'MOV.FMT',
              'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
              'short': 'Floating Point Move'}],
 'MOVF': [{'instr': 'MOVF',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move Conditional on Floating Point False'}],
 'MOVF.FMT': [{'instr': 'MOVF.FMT',
               'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
               'short': 'Floating Point Move Conditional on Floating Point False'}],
 'MOVN': [{'instr': 'MOVN',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move Conditional on Not Zero'}],
 'MOVN.FMT': [{'instr': 'MOVN.FMT',
               'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
               'short': 'Floating Point Move Conditional on Not Zero'}],
 'MOVT': [{'instr': 'MOVT',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move Conditional on Floating Point True'}],
 'MOVT.FMT': [{'instr': 'MOVT.FMT',
               'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
               'short': 'Floating Point Move Conditional on Floating Point True'}],
 'MOVZ': [{'instr': 'MOVZ',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move Conditional on Zero'}],
 'MOVZ.FMT': [{'instr': 'MOVZ.FMT',
               'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
               'short': 'Floating Point Move Conditional on Zero'}],
 'MSUB': [{'instr': 'MSUB',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Multiply and Subtract Word to Hi, Lo'}],
 'MSUB.FMT': [{'instr': 'MSUB.FMT',
               'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
               'short': 'Floating Point Multiply Subtract'}],
 'MSUBU': [{'instr': 'MSUBU',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Multiply and Subtract Unsigned Word to Hi, Lo'}],
 'MTC0': [{'instr': 'MTC0',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move to Coprocessor 0'}],
 'MTC1': [{'instr': 'MTC1',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move Word to Floating Point'}],
 'MTC2': [{'instr': 'MTC2',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move Word to Coprocessor 2'}],
 'MTHI': [{'instr': 'MTHI',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move To HI Register'}],
 'MTLO': [{'instr': 'MTLO',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Move To LO Register'}],
 'MUL': [{'instr': 'MUL',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Multiply Word to GPR'}],
 'MUL.FMT': [{'instr': 'MUL.FMT',
              'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
              'short': 'Floating Point Multiply'}],
 'MULT': [{'instr': 'MULT',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Multiply Word'}],
 'MULTU': [{'instr': 'MULTU',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Multiply Unsigned Word'}],
 'NEG.FMT': [{'instr': 'NEG.FMT',
              'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
              'short': 'Floating Point Negate'}],
 'NMADD.FMT': [{'instr': 'NMADD.FMT',
                'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
                'short': 'Floating Point Negative Multiply Add'}],
 'NMSUB.FMT': [{'instr': 'NMSUB.FMT',
                'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
                'short': 'Floating Point Negative Multiply Subtract'}],
 'NOP': [{'instr': 'NOP',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'No Operation'}],
 'NOR': [{'instr': 'NOR',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Not Or'}],
 'OR': [{'instr': 'OR',
         'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
         'short': 'Or'}],
 'ORI': [{'instr': 'ORI',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Or Immediate'}],
 'PREF': [{'instr': 'PREF',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Prefetch'}],
 'RECIP.FMT': [{'instr': 'RECIP.FMT',
                'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
                'short': 'Reciprocal Approximation'}],
 'ROUND.W.FMT': [{'instr': 'ROUND.W.FMT',
                  'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
                  'short': 'Floating Point Round to Word Fixed Point'}],
 'RSQRT.FMT': [{'instr': 'RSQRT.FMT',
                'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
                'short': 'Reciprocal Square Root Approximation'}],
 'SB': [{'instr': 'SB',
         'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
         'short': 'Store Byte'}],
 'SC': [{'instr': 'SC',
         'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
         'short': 'Store Conditional Word'}],
 'SD': [{'instr': 'SD',
         'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
         'short': 'Store Doubleword'}],
 'SDBBP': [{'instr': 'SDBBP',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Software Debug Breakpoint'}],
 'SDC1': [{'instr': 'SDC1',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Store Doubleword from Floating Point'}],
 'SDC2': [{'instr': 'SDC2',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Store Doubleword from Coprocessor 2'}],
 'SH': [{'instr': 'SH',
         'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
         'short': 'Store Halfword'}],
 'SLL': [{'instr': 'SLL',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Shift Word Left Logical'}],
 'SLLV': [{'instr': 'SLLV',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Shift Word Left Logical Variable'}],
 'SLT': [{'instr': 'SLT',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Set on Less Than'}],
 'SLTI': [{'instr': 'SLTI',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Set on Less Than Immediate'}],
 'SLTIU': [{'instr': 'SLTIU',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Set on Less Than Immediate Unsigned'}],
 'SLTU': [{'instr': 'SLTU',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Set on Less Than Unsigned'}],
 'SQRT': [{'instr': 'SQRT',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Floating Point Square Root'}],
 'SRA': [{'instr': 'SRA',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Shift Word Right Arithmetic'}],
 'SRAV': [{'instr': 'SRAV',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Shift Word Right Arithmetic Variable'}],
 'SRL': [{'instr': 'SRL',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Shift Word Right Logical'}],
 'SRLV': [{'instr': 'SRLV',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Shift Word Right Logical Variable'}],
 'SSNOP': [{'instr': 'SSNOP',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Superscalar No Operation'}],
 'SUB': [{'instr': 'SUB',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Subtract Word'}],
 'SUB.FMT': [{'instr': 'SUB.FMT',
              'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
              'short': 'Floating Point Subtract'}],
 'SUBU': [{'instr': 'SUBU',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Subtract Unsigned Word'}],
 'SW': [{'instr': 'SW',
         'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
         'short': 'Store Word'}],
 'SWC1': [{'instr': 'SWC1',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Store Word from Floating Point'}],
 'SWC2': [{'instr': 'SWC2',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Store Word from Coprocessor 2'}],
 'SWL': [{'instr': 'SWL',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Store Word Left'}],
 'SWR': [{'instr': 'SWR',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Store Word Right'}],
 'SYNC': [{'instr': 'SYNC',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Synchronize Shared Memory'}],
 'SYSCALL': [{'instr': 'SYSCALL',
              'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
              'short': 'System Call'}],
 'TEQ': [{'instr': 'TEQ',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Trap if Equal'}],
 'TEQI': [{'instr': 'TEQI',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Trap if Equal Immediate'}],
 'TGE': [{'instr': 'TGE',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Trap if Greater or Equal'}],
 'TGEI': [{'instr': 'TGEI',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Trap if Greater of Equal Immediate'}],
 'TGEIU': [{'instr': 'TGEIU',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Trap if Greater or Equal Immediate Unsigned'}],
 'TGEU': [{'instr': 'TGEU',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Trap if Greater or Equal Unsigned'}],
 'TLBP': [{'instr': 'TLBP',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Probe TLB for Matching Entry'}],
 'TLBR': [{'instr': 'TLBR',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Read Indexed TLB Entry'}],
 'TLBWI': [{'instr': 'TLBWI',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Write Indexed TLB Entry'}],
 'TLBWR': [{'instr': 'TLBWR',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Write Random TLB Entry'}],
 'TLT': [{'instr': 'TLT',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Trap if Less Than'}],
 'TLTI': [{'instr': 'TLTI',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Trap if Less Than Immediate'}],
 'TLTIU': [{'instr': 'TLTIU',
            'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
            'short': 'Trap if Less Than Immediate Unsigned'}],
 'TLTU': [{'instr': 'TLTU',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Trap if Less Than Unsigned'}],
 'TNE': [{'instr': 'TNE',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Trap if Not Equal'}],
 'TNEI': [{'instr': 'TNEI',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Trap if Not Equal Immediate'}],
 'TRUNC.W.FMT': [{'instr': 'TRUNC.W.FMT',
                  'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
                  'short': 'Floating Point Truncate to Word Fixed Point'}],
 'WAIT': [{'instr': 'WAIT',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Enter Standby Mode'}],
 'XOR': [{'instr': 'XOR',
          'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
          'short': 'Exclusive Or'}],
 'XORI': [{'instr': 'XORI',
           'link': 'https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf',
           'short': 'Exclusive Or Immediate'}]}

def find_proper_name(instruction):
    out = str(instruction).strip().upper()
    return out

def get_doc_url(i):
    """ Takes in the instruction tokens and returns [(short form, doc url)] """
    names = map(find_proper_name, i) # handles instruction prefixes
    output = []
    for name in names:
        if name in instrs.keys():
            inst_data = instrs[name][0]
            output.append((inst_data['short'], inst_data['link']))
    # For 90% of instructions, output could just be a tuple and we could be done with it.
    # However, the lock and rep* prefixes should be documented too (to prevent major "WTH" moments)
    # so we have to structure everything around having a list of results
    return output
